# Generated by Django 4.0.2 on 2024-02-11 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_job_processedfile_alter_document_docfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='ProcessedFile',
        ),
    ]
